

export const AllHelmets = [
  {
    id:"1",
    title: "Axor Apex Solid ISI ECE DOT Certified Glossy Black",
    size: "Mediam",
    img: "https://m.media-amazon.com/images/I/413ra3D+0gL.AC_SX250.jpg",
    newPrice: "4449",
    company: "Axor",
    color: "black",
    category: "FullFace"
  },
  {
    id:"2",
    img: "https://m.media-amazon.com/images/I/61ntAvlcJML._AC_UL320_.jpg",
    title: "Axor X Cross ISI DOT Road Helmet the smuff",
    newPrice: "5199",
    company: "Axor",
    color: "White",
    category: "OffRoad",
  },


  {
    id:"3",
    img: "https://m.media-amazon.com/images/I/41LT0AuviIL._AC_UL320_.jpg",
    title: "SMK Allterra Full face Offroad Helment Fulmine GL 174",
    newPrice: "4999",
    company: "SMK",
    color: "green",
    category: "OffRoad",
  },
  {
    id:"4",
    img: "https://m.media-amazon.com/images/I/61V1pB-2JRL._AC_UL320_.jpg",
    title: "Ignyte IGN-4 Trever ISI / DOT Certified Anti-Fog Clear Visor",
    newPrice: "2500",
    company: "Ignyte",
    color: "black",
    category: "FullFace",
  },
  {
    id:"5",
    img: "https://m.media-amazon.com/images/I/61rb+PpZtqL._AC_UL320_.jpg",
    title: "SMK Helmets - FF320 Stream Evo - Neon - Gloss Black Blue hhdf",
    newPrice: "3599",
    company: "SMK",
    color: "green",
    category: "FullFace",
    
  },
  {
    id:"6",
    img: "https://m.media-amazon.com/images/I/61FudCk-2rL._AC_UL320_.jpg",
    title: "SMK ALLTERRA Off Road Helmets ISI DOT ECE Certified",
    newPrice: "4999",
    company: "SMK",
    color: "black",
    category: "OffRoad",
  },

  {
    id:"7",
    img: "https://m.media-amazon.com/images/I/61amoP4HGxL._AC_UL320_.jpg",
    title: "LS2 Helmets - FF800 Storm - Racer - Gloss White Red Blue - Dual Visor",
    newPrice: "10700",
    company: "LS2",
    color: "white",
    category: "FullFace",
  },

  {
    id:"8",
    img: "https://m.media-amazon.com/images/I/41ISl58N-OL._AC_UL320_.jpg",
    title: "SMK Helmets - Typhoon - Unicolour - ISI DOT EEC Certified",
    newPrice: "3899",
    company: "SMK",
    color: "green",
    category: "FullFace",
  },

  {
    id:"9",
    img: "https://m.media-amazon.com/images/I/61kEeBDS8vL._AC_UL320_.jpg",
    title: "Steelbird SBH-17 Terminator ISI Certified Matt Finish  Graphic",
    newPrice: "1899",
    company: "SteelBird",
    color: "blue",
    category: "FullFace",
  },

  {
    id:"10",
    img: "https://m.media-amazon.com/images/I/812X5+dg6WL._AC_UL320_.jpg",
    title: "Steelbird SBA-8 Crazy Wheel ISI Certified Flip-Up Helmet ",
    newPrice: "2139",
    company: "SteelBird",
    color: "green",
    category: "FullFace",
   
  },
  {
    id:"11",
    img: "https://m.media-amazon.com/images/I/81NA1H-xMFL._AC_UL320_.jpg",
    title: "LS2 Helmets - FF320 Stream Evo - Neon - Gloss Black Blue Fluo Green",
    newPrice: "4399",
    company: "LS2",
    color: "red",
    category: "FullFace",
  },
  {
    id:"12",
    img: "https://m.media-amazon.com/images/I/510rjZxQWIL._AC_UL320_.jpg",
    title: "Ignyte IGN-4 ISI / DOT Certified Double Visor Outer Anti-Fog Clear",
    newPrice: "3700",
    company: "Ignyte",
    color: "black",
    category: "FullFace",
  },
  {
    id:"13",
    img: "https://m.media-amazon.com/images/I/61v40WTZQ0L._AC_UL320_.jpg",
    title: "Vega Off Road Sketch ISI Certified Matt Dual Visor Outer Clear",
    newPrice: "1900",
    company: "Vega",
    color: "white",
    category: "OffRoad",
  },
  {
    id:"14",
    img: "https://m.media-amazon.com/images/I/61du5cz8+GL._AC_UL320_.jpg",
    title: "Vega Bolt Bunny Full Face Helmet Dull Black Orange",
    newPrice: "1800",
    company: "Vega",
    color: "black",
    category: "FullFace",
  },

  {
    id:"15",
    img: "https://m.media-amazon.com/images/I/51m9XJjWyYL._AC_UL320_.jpg",
    title: "Axor Helmets Street Panther Helmet (Dull Black Grey, Large)",
    newPrice: "4500",
    company: "Axor",
    color: "green",
    category: "FullFace",
  },
  {
    id:"16",
    img: "https://m.media-amazon.com/images/I/91SIqmEXXuL._AC_UL320_.jpg",
    title: "Steelbird SBA-1 Beast ABS Glossy White and Green Helmet",
    newPrice: "1999",
    company: "SteelBird",
    color: "red",
    category: "FullFace",
  },
  {
    id:"17",
    img: "https://m.media-amazon.com/images/I/71s21oNOj9L._AC_UL320_.jpg",
    title: "Steelbird SBH-23 Brutal ISI Certified Open Face Helmet",
    newPrice: "500",
    company: "SteelBird",
    color: "white",
    category: "HalfFace",
  },
  {
    id:"18",
    img: "https://m.media-amazon.com/images/I/71Sx30JUpeL._AC_UL320_.jpg",
    title: "Vega Cruiser ISI Certified Lightweight & Compact with",
    newPrice: "599",
    company: "Vega",
    color: "blue",
    category: "HalfFace",
  },
  {
    id:"19",
    img: "https://m.media-amazon.com/images/I/515fbKW3lJL._AC_UL320_.jpg",
    title: "SMK Typhoon Thron Full face Helmet for Bike",
    newPrice: "5299",
    company: "SMK",
    color: "black",
    category: "FullFace",
  },
  {
    id:"20",
    img: "https://m.media-amazon.com/images/I/51GFPANkoDL._AC_UL320_.jpg",
    title: "Ignyte go Ignyte IGN-4 ISI / DOT Certified ",
    newPrice: "399",
    company: "Ignyte",
    color: "black",
    category: "HalfFace",
  }
  
];
